### ISSUE TITLE
IFile.Open(Read) cannot be mocked with NSubstitute anymore due to System.IO.Abstractions.FileSystemStream 

### ISSUE THREAD

**Issue by rklec** [TestableIO/System.IO.Abstractions#1009]
**Describe the bug**
I am upgrading from System.IO.Abstractions v17.0.18 to v19.2.29.

**To Reproduce**
```csharp
using System.IO;
using System.IO.Abstractions;
using System.IO.Abstractions.TestingHelpers;

// ...
        [Test]
        public async Task FileSystemStreamBrokenTest()
        {
            var fileSystem = Substitute.For<IFileSystem>();
            var fileStream = System.IO.Abstractions.FileSystemStream.Null;
            fileSystem.File.OpenRead(default!).ReturnsForAnyArgs(fileStream);

            fileSystem.File.OpenRead("somePath");
        }
```

This fails with an NSubsitute error though:
![grafik](https://github.com/TestableIO/System.IO.Abstractions/assets/71322635/4b416dd9-ae19-46b7-afc5-30ef57497e4e)

Also, Resharper suggests to simplify it in a way that it is essentially the same as this:
```csharp
        [Test]
        public async Task FileSystemStreamBrokenTest()
        {
            var fileSystem = Substitute.For<IFileSystem>();
            var fileStream = System.IO.Stream.Null;
            fileSystem.File.OpenRead(default!).ReturnsForAnyArgs(fileStream);

            fileSystem.File.OpenRead("somePath");
        }
 ```
 
 ...which may explain why it fails.

Before all that I had a custom class for `fileStream`, which just also had the most common stuff implemented, so it was like your mock, except of the special type. Now the types don't match ([I guess since v18.0.2](https://github.com/TestableIO/System.IO.Abstractions/releases/tag/v18.0.1)) and as such I need to adapt it...

I tried this, too:
```csharp
        [Test]
        public async Task FileSystemStreamBrokenTest()
        {
            var fileSystem = Substitute.For<IFileSystem>();

            var fileStream = new MockFileStreamFactory(new MockFileSystem()).New("anything.example", FileMode.Open);
            fileSystem.File.OpenRead(default!).ReturnsForAnyArgs(fileStream);

            fileSystem.File.OpenRead("anything.example");
        }
```

but that (kinda correctly) fails with:
> System.IO.FileNotFoundException : Could not find file 'anything.example'.

....but I just wanna mock "any file", I don't care about what content etc.

**Expected behavior**
`System.IO.Abstractions.FileSystemStream.Null` should be useful as a wrapper, when you really don't care about your file handle/anything, but _just_ want to mock it. I also don't wanr to mock a whole file system and provide any/all files in it, like I likely could with `MockFileSystem`.

**Additional context**
Finally found a workaround as `.` always exists:

```csharp
        [Test]
        public async Task FileSystemStreamBrokenTest()
        {
            var fileSystem = Substitute.For<IFileSystem>();

            var fileStream = new MockFileStreamFactory(new MockFileSystem()).New(".", FileMode.Open);
            fileSystem.File.OpenRead(default!).ReturnsForAnyArgs(fileStream);

            fileSystem.File.OpenRead(".");
        }
```

IMHO there should be a more convenient way though.

## System

```xml
		<PackageReference Include="System.IO.Abstractions" Version="19.2.29" />
		<PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="19.2.29" />
```

and NSubstitute 4.4.0

**Comment by fgreinacher** [comment]
Thanks for the report. I think we should shadow the `Stream.Null` field in our [base class](https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/TestableIO.System.IO.Abstractions/FileSystemStream.cs#L11).

Contributions welcome :)

**Comment by sheila-stewart** [comment]
This is how I'm working around the issue, in case it can help anyone else:
```
/// <summary>
///     Wrapper around a <see cref="Stream"/> with no backing store, which
///     is used as a replacement for a <see cref="FileSystemStream"/>. As
///     such it implements the same properties and methods as a <see cref="FileSystemStream"/>.
/// </summary>
public class NullFileSystemStream : FileSystemStream
{
    /// <inheritdoc cref="Stream.Null" />
    public static new NullFileSystemStream Null { get; } = new NullFileSystemStream();

    /// <summary>
    ///     Initializes a new instance of <see cref="NullFileSystemStream" />.
    /// </summary>
    private NullFileSystemStream() : base(Stream.Null, ".", true)
    { }
}
```

**Comment by vbreuss** [comment]
> Thanks for the detailed report!
> 
> I think we should shadow the `Stream.Null` field in our [base class](https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/TestableIO.System.IO.Abstractions/FileSystemStream.cs#L11).
> 
> Contributions welcome :)

@fgreinacher: I don't think it would be a good idea, to add a test helper in the interface project. But we could add an option to simply create a "Null-Stream" similar to the solution from @sheila-stewart  to the TestingHelpers project.

**Comment by fgreinacher** [comment]
> > I think we should shadow the `Stream.Null` field in our [base class](https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/TestableIO.System.IO.Abstractions/FileSystemStream.cs#L11).
> 
> @fgreinacher: I don't think it would be a good idea, to add a test helper in the interface project. But we could add an option to simply create a "Null-Stream" similar to the solution from @sheila-stewart to the TestingHelpers project.

@vbreuss Why do you consider this a test helper? The `Null` stream is exposed by the base class and we should provide a working wrapper I think?

**Comment by vbreuss** [comment]
> @vbreuss Why do you consider this a test helper? The `Null` stream is exposed by the base class and we should provide a working wrapper I think?

@fgreinacher:
The interface wraps a [`FileStream`](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream) which does not have a static [`Null`](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.null) property itself, but only the base type, which returns a `Stream` and not a `FileStream`.
![image](https://github.com/TestableIO/System.IO.Abstractions/assets/3438234/56d5f697-c7c3-4ba7-919f-ea1843adeff1)

If we include this in the interface, we add something that is not there in the real file system.

I think it a good idea to simplify creating a Null-FileSystemStream, but I would add this to the TestingHelper project and not to the interface project itself.

**Comment by sheila-stewart** [comment]
Maybe add the ability to mock a stream with no backing store like this:

`var nullStream = new MockFileStreamFactory(new MockFileSystem()).Null;`

**Comment by sheila-stewart** [comment]
Awesome, thanks!
