### ISSUE TITLE
MockFileSystem: IFile.GetLastWriteTimeUtc may return wrong last write time after calling IFileInfo.Open

### ISSUE THREAD

**Issue by jhinder** [TestableIO/System.IO.Abstractions#1029]
**Describe the bug**
`IFile.GetLastWriteTimeUtc` returns the system time instead of `MockFileData`'s `LastWriteTime` value if `IFileInfo.Open` was called with `File.Open` but without `FileAccess.Read`.

**To Reproduce**
```csharp
using System.Diagnostics;
using System.IO.Abstractions.TestingHelpers;

// Setup
const string path = @"C:\test.file";
var mockFs = new MockFileSystem();
var lastWriteTime = new DateTime(2023, 08, 22, 10, 30, 00, DateTimeKind.Utc);
Console.WriteLine("Expected write time: {0}", lastWriteTime);
mockFs.AddFile(path, new MockFileData("test") { LastWriteTime = lastWriteTime });

// Act
var file = mockFs.FileInfo.New(path);
using (file.Open(FileMode.Open)) { }

// Assert
var fileInfoWriteTime = file.LastWriteTimeUtc;
Console.WriteLine("LastWriteTimeUtc from property: {0}", fileInfoWriteTime);
Debug.Assert(fileInfoWriteTime == lastWriteTime);

var fileWriteTime = mockFs.File.GetLastWriteTimeUtc(file.FullName);
Console.WriteLine("LastWriteTimeUtc from call: {0}", fileWriteTime);
Debug.Assert(fileWriteTime == lastWriteTime);
```

The code returns an output similar to this, and the last assertion is hit:
```
Expected write time: 22.08.2023 10:30:00
LastWriteTimeUtc from property: 22.08.2023 10:30:00
LastWriteTimeUtc from call: 22.08.2023 08:44:14
```

**Expected behavior**
The correct write time (= the time set in the `MockFileData` initializer) is returned in all cases.

**Additional context**
Removing the call to `Open` or adding the `FileAccess.Read` argument both lead to correct behaviour.

**Comment by vbreuss** [comment]
@jhinder :
In #875 I implemented that on access to a file the LastWriteTime is set accordingly. Per default it uses the current DateTime, but you can overwrite this behaviour by setting [`MockFileSystem.MockTime()`](https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/TestableIO.System.IO.Abstractions.TestingHelpers/MockFileSystem.cs#L116).

**Comment by fgreinacher** [comment]
I think the answer above allows you to make it work for you, so I'm closing this. Feel free to reopen if anything is missing!
