### ISSUE TITLE
BinaryFormatter becomes obsolete -> Remove it with .NET 8.0

### ISSUE THREAD

**Issue by vbreuss** [TestableIO/System.IO.Abstractions#1033]
I tried executing the preview version of .NET 8.0 with System.IO.Abstractions and got the following test errors (see #1032)
![image](https://github.com/TestableIO/System.IO.Abstractions/assets/3438234/097bdfa8-7eeb-40b1-8716-c32180101101)

The reason is, that the [`BinaryFormatter` becomes obsolete](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md).

I suggest to remove the support for Serialization under .NET8.0.

**Comment by fgreinacher** [comment]
Finally they did it 😅

Yes, let's exclude it for the .NET 8 build!
