### ISSUE TITLE
Creating new MockFileInfo thinks file exists when it actually does not.

### ISSUE THREAD

**Issue by AnakinRaW** [TestableIO/System.IO.Abstractions#1072]
**Describe the bug**
Creating a new `MockFileInfo` behaves differently to creating a new `FileInfo` under certain circumstances. 

**To Reproduce**
```
var mfs = new MockFileSystem();
mfs.AddEmptyFile("file"); // This file exists to distract the mocking file system.

var fi = mfs.FileInfo.New("file/"); // fi created from a directory path.

Assert.AreEqual(string.Empty, fi.Name); // This test passes.
Assert.IsFalse(fi.Exists); // Fails, cause MockFileInfo thinks the file exists
```

**Expected behavior**

**Additional context**
The "bug" exists, because the `MockFileInfo::Refresh()` calls `MockFileInfo::GetFile(path)`. 
This method normalizes the path by removing trailing path separators. 

When passing a directory path to `FileInfo`, .NET treats file info as an empty-name file inside the specified directory.

**Comment by vbreuss** [comment]
@AnakinRaW :
I am not able to reproduce your issue.

I created a test that runs against the real file system on all platforms (see https://github.com/Testably/Testably.Abstractions/pull/442):
```csharp
	[Fact]
	public void Reproduce_Issue1072()
	{
		FileSystem.File.WriteAllText("file", ""); // This file exists to distract the mocking file system.

		var fi = FileSystem.FileInfo.New("file/"); // fi created from a directory path.

		fi.Name.Should().Be(string.Empty);
		fi.Exists.Should().BeTrue();
	}
```

The test only passes after I changed the last line to test that `fi.Exists` is `true` and then it passes on all platforms.

Can you please help me, reproducing this issue?

**Comment by AnakinRaW** [comment]
Ok, i just double checked this, and i'm unsure how i ended up writing this issue 😶
I can't repro either... 

Sorry for that one

**Comment by fgreinacher** [comment]
> Ok, i just double checked this, and i'm unsure how i ended up writing this issue 😶 I can't repro either...
> 
> Sorry for that one

No worries, feel free to reopen if needed!
