### ISSUE TITLE
I want to step out of this project

### ISSUE THREAD

**Issue by fgreinacher** [TestableIO/System.IO.Abstractions#1080]
I have originally started maintaining this project because I used it heavily in my day job.

Over the time I have changed jobs and technology stacks so this is not really the case anymore.

I'm therefore looking for someone to take over the ownership of this project and the `TestableIO` org.

Let me know if you are interested and/over have any other feedback.

@jpreese You are still an owner of the org, let me know if you want to keep it like that!

**Comment by vbreuss** [comment]
Sorry to hear this, @fgreinacher!

As my own project relies on the TestableIO interfaces, I would be interested in keeping this project up and running and would gladly help maintaining it.

**Comment by jpreese** [comment]
I'm in the same boat as you, @fgreinacher -- It has been quite some time since I've actively worked with C# in my day to day.

I don't mind keeping ownership to assist with administrative tasks here and there, but it would be better for the project as a whole to work on finding a replacement for you. Thanks for all you've done!

**Comment by fgreinacher** [comment]
Thanks a ton for your feedback folks!

@vbreuss Great to hear that your willing to take this over. I was hoping for it since you have been the most active contributor here for quite some time :) I will give you all the necessary permissions over the next days.

**Comment by fgreinacher** [comment]
@vbreuss I have sent you an invite for the GitHub org. What's your username on https://www.nuget.org?

**Comment by vbreuss** [comment]
> What's your username on https://www.nuget.org?

@fgreinacher:
My username is [vbreuss](https://www.nuget.org/profiles/vbreuss).

**Comment by fgreinacher** [comment]
Thanks, added you there too.

**Comment by fgreinacher** [comment]
Thanks again for taking over here @vbreuss, I'm sure you'll do a great job evolving this!

I will remove myself from the orgs now. Feel free to ping me anytime if you need help.

**Comment by fgreinacher** [comment]
Oh, and @vbreuss it seems you need to unpin this issue, I assumed it would happen automatically when closing it.

**Comment by vbreuss** [comment]
@fgreinacher , @jpreese 
It seems we have a little problem here.
As I am not an owner of this organization, I cannot see/change the settings or pin/unpin this issue.
Can you please change this, before you leave?

**Comment by fgreinacher** [comment]
I already left 🤦 

I thought I added you to `TestableIO`, probably I messed up with the role.

@jpreese Can you check please? 🙇

**Comment by fgreinacher** [comment]
> I already left 🤦
> 
> I thought I added you to `TestableIO`, probably I messed up with the role.
> 
> @jpreese Can you check please? 🙇

@jpreese Sorry for pinging again, but I think it would be good to have this resolved :) Thanks a ton!

**Comment by jpreese** [comment]
@vbreuss @fgreinacher done. I've added @vbreuss as an owner of the organization, which should give the necessary rights to this repository as well.

**Comment by vbreuss** [comment]
Thanks a lot, @jpreese.
It now works!
