### ISSUE TITLE
Cannot access a closed Stream on v21.1.2

### ISSUE THREAD

**Issue by rouke-broersma** [TestableIO/System.IO.Abstractions#1162]
**Describe the bug**
Updating to v21.1.2 causes stream closed exceptions in our unit tests on dispose of the stream after it has already been closed or disposed by (I assume) System.Text.Json. I don't think we are using this wrong, but if I apologize in advance if this is user error.

Exception occurs on dispose after return of this line: https://github.com/stryker-mutator/stryker-net/blob/b7f9ccac7e384b14f7c21321006cbae4261f6d56/src/Stryker.Core/Stryker.Core/Baseline/Providers/DiskBaselineProvider.cs#L38

The stream is not used anywhere after that.

**To Reproduce**
Run unit tests Stryker.Core.UnitTest.Baseline.Providers: https://github.com/stryker-mutator/stryker-net/pull/3100 

**Expected behavior**
Disposing of FileStream should not cause an exception

**Additional context**

Stream appears to still be open

![image](https://github.com/user-attachments/assets/a4f869a9-6e39-49d9-bf5b-acee562d9114)

Exception on dispose

![image](https://github.com/user-attachments/assets/dbe1ac26-3747-457d-a186-e6af6645613c)

**Comment by vbreuss** [comment]
Sorry, @rouke-broersma, there must have slipped an issue with `DisposeAsync`.
I could reproduce the issue with the following minimal example:
```csharp
  var fileSystem = new MockFileSystem();
  fileSystem.File.WriteAllText("foo.txt", "");
  {
      await using var reportStream = fileSystem.File.OpenRead("foo.txt");
  }
```

Will release a fix immediately!
