### ISSUE TITLE
MockFileSystem.Path.GetTempPath() returns temp directory with no trailing DirectorySeparatorChar

### ISSUE THREAD

**Issue by ssi-rbarcebal** [TestableIO/System.IO.Abstractions#1171]
**Describe the bug**
When getting the temp path, the returned directory string does not end with DirectorySeparatorChar.

**To Reproduce**
```
var fileSystem = new MockFileSystem();
var tempDir = fileSystem.Path.GetTempPath();
```
Value of tempDir = "/temp"

**Expected behavior**
Should be tempDir = "/temp/"

**Additional context**
Using .NET 8 MacOS. Same issue on Windows but with drive letter.
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-8.0&tabs=linux

**Comment by vbreuss** [comment]
Thanks for reporting. I will have a look at it shortly. As a workaround you could also use the `MockFileSystem` from [Testably.Abstractions](https://github.com/Testably/Testably.Abstractions).
