### ISSUE TITLE
Discrepancy between DirectoryInfo(Base).Exists in real file system and MockFileSystem DirectoryInfoBase.Exists

### ISSUE THREAD

**Issue by m-ringler** [TestableIO/System.IO.Abstractions#661]
**Describe the bug**
System.IO.DirectoryInfo.Exists seems to store the "exists" information at the time of creation. MockFileSystem seems to use up-to-date information.

**To Reproduce**
~~~
        public void MockFileSystemDirectoryInfoExists_AfterCreate_ShouldBeFileSystemDirectoryInfoExists()
        {
            var folder = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            var di = new DirectoryInfo(folder);
            Debug.Assert(!di.Exists, "!di.Exists");
            di.Create();

            var mfs = new MockFileSystem();
            var di_mfs = mfs.DirectoryInfo.FromDirectoryName(folder);
            Debug.Assert(!di_mfs.Exists, "!di_mfs.Exists");
            di_mfs.Create();

            di_mfs.Exists.Should().Be(di.Exists);
        }
~~~

**Expected behavior**
Mock File System should behave like the real file system.

**Additional context**
.NET 4.6.2; System.IO.Abstractions 3.0.2

**Comment by m-ringler** [comment]
See also: https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.refresh?view=netframework-4.6.2

**Comment by fgreinacher** [comment]
Interesting, thanks for reporting!
