### ISSUE TITLE
MockFileSystem does not support Root directories

### ISSUE THREAD

**Issue by derecskey** [TestableIO/System.IO.Abstractions#702]
**Describe the bug**
Including a Root drive/directory in a MockFileSystem causes ArgumentNullException at line 82 of MockFileSystem.cs

**To Reproduce**
To recreate, execute the following line of code:

```csharp
var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
{
    { @"c:\demo", new MockDirectoryData() },
    { @"z:\", new MockDirectoryData() },
    { @"Z:\foo", new MockDirectoryData() }
});
```

**Expected behavior**

"Z:\" should be a valid directory.

**Additional context**

```csharp
var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
{
    { @"c:\demo", new MockDirectoryData() },
    //{ @"z:\", new MockDirectoryData() },
    { @"Z:\foo", new MockDirectoryData() }
});  //This produces no exception

var fileSystem = new MockFileSystem(new Dictionary<string, MockFileData>
{
    { @"c:\demo", new MockDirectoryData() },
    //{ @"z:\", new MockDirectoryData() },
    { @"Z:\foo", new MockDirectoryData() }
});  //This produces an exception.
```

**Comment by fgreinacher** [comment]
Thanks for reporting!

**Comment by tuan-tu-tran** [comment]
Hi, in the _Additional context_  section, the 2 examples are the same even though the comments say the 1st one does not throw an exception whereas the 2nd does.

I think in the 2nd example, the 2nd directory mock should not be commented, just like in the _To reproduce_ section

For reference, the exception thrown is

> System.ArgumentNullException: Value cannot be null. (Parameter 'key')

And here's the stack trace:
```
Dictionary`2.FindValue(TKey key)
Dictionary`2.TryGetValue(TKey key, TValue& value)
MockFileSystem.DirectoryExistsWithoutFixingPath(String path)
MockFileSystem.AddFile(String path, MockFileData mockFile)
MockFileSystem.ctor(IDictionary`2 files, String currentDirectory)
```

**Comment by vladimir-shirmanov** [comment]
Hi guys, I added a PR to resolve this bug, can somebody take a look when you have time @fgreinacher

**Comment by vbreuss** [comment]
@vladimir-shirmanov : Thanks for providing a pull request.

Note: @fgreinacher is no longer active in this project (see #1080), but I reviewed your pull request...
