### ISSUE TITLE
Using the MoveTo function to move a mocked directory doesn't update the DirectoryInfo information

### ISSUE THREAD

**Issue by SamirAL89** [TestableIO/System.IO.Abstractions#736]
**Describe the bug**
In a unit test which consists on moving directory using the MoveTo function from IDirectoryInfo doesn't update the IDirectoryInfo entries and the moved directory info keeps the same initial values. However using the same function on the debug and release modes( FileSystem) does update the fields and properties of the DirectorytInfo

**To Reproduce**
1. Mock a directory 
2. Initialize DirectoryInfo
3. Move the directory to a new destination
4. Compare the path of the current directory and the destination path.

**Expected behavior**
The moved mocked directory is updated to new state (new path).

**Comment by fgreinacher** [comment]
Thanks for reporting!
