### ISSUE TITLE
Can't see XML documentation.

### ISSUE THREAD

**Issue by Tum4ik** [TestableIO/System.IO.Abstractions#743]
**Describe the bug**
The VS intellisense does not show the XML documentation.

**To Reproduce**
1. Use any interface or method.
2. Place mouse cursor over the interface or method.
3. The XML documentation is missing.

**Expected behavior**
The XML documentation should be visible.

**Additional context**
![image](https://user-images.githubusercontent.com/21317790/126334624-8cfe6f44-8c3b-47f8-9ec4-d26100b167a0.png)
![image](https://user-images.githubusercontent.com/21317790/126334679-64d5909d-47e3-4214-a22e-3c00bb02dda4.png)

**Comment by fgreinacher** [comment]
Thanks for the report. Actually the `inheritdoc` tags should be expanded by the reference at https://github.com/System-IO-Abstractions/System.IO.Abstractions/blob/main/Directory.Build.props#L26

**Comment by Tum4ik** [comment]
I think the problem is that the xml file is not distributed with the nuget package.

![image](https://user-images.githubusercontent.com/21317790/126761033-89c4db8a-a415-472f-9132-bdbdfc243d16.png)
