### ISSUE TITLE
Directory.GetFileSystemEntries is missing the SearchOption parameter

### ISSUE THREAD

**Issue by StarWars999123** [TestableIO/System.IO.Abstractions#775]
The windows method for Directory.GetFileSystemEntries supports a parameter SearchOption to return not only values of the top most entries, but also the possibility to search within all sub directories. However, the mock hereby has no option for it yet. 

It would be great to use this method here. Is there a chance, that you add this functionality?

(Function gets used within a .Net Core ASP.NET MVC application)

**Comment by StarWars999123** [comment]
I was able to circumvent the usage of this parameter by the help of the following method: https://stackoverflow.com/a/25923435/4169550

A quick fix would be great anyway.

**Comment by fgreinacher** [comment]
Thanks for the issue! [We're currently missing this overload in our API](https://github.com/TestableIO/System.IO.Abstractions/blob/main/tests/System.IO.Abstractions.Tests/__snapshots__/ApiParityTests.Directory_.NET%206.0.snap). We can tackle this together with #774.

**Comment by rkm** [comment]
I should be able to take a look at this over the weekend
