### ISSUE TITLE
IFile.Create has different return type than File.Create

### ISSUE THREAD

**Issue by Heldenkrieger01** [TestableIO/System.IO.Abstractions#779]
**Describe the bug**
The `IFile.Create()` method returns a `Stream`, but the "original" `File.Create()` returns a `FileStream`. This is important, because the `FileStream` contains the `Name`-property with the files name.

**Expected behavior**
`IFile.Create()` returns a `FileStream`.

**Comment by fgreinacher** [comment]
This is more or less by design, because `FileStream` relies on the real file system.

We could return a custom subclass of `Stream` that adds the `Name` property.

What do you think about this?

**Comment by Heldenkrieger01** [comment]
That would be great, especially for people like me, that move to Abstractions with existing code.

**Comment by fgreinacher** [comment]
Cool, so let's make this as ready and discuss details in a PR, once somebody finds the time to work on this 👍

**Comment by vbreuss** [comment]
I think this issue can be closed, as the `FileSystemStream` was implemented in #906 ...
Do you agree, @Heldenkrieger01 ?

**Comment by fgreinacher** [comment]
I'm closing this. Feel free to reopen if needed!
