### ISSUE TITLE
👉 Maintainers wanted 

### ISSUE THREAD

**Issue by fgreinacher** [TestableIO/System.IO.Abstractions#781]
I am currently maintaining this project alone and don't really use it in my day job anymore. Therefore I can only invest a minimal amount of time for answering issues, reviewing PRs and building new features.

It would be awesome if I could find one or two other maintainers so that this project gets the love it deserves.

Please answer here if you would be willing to help! Don't worry if you have no previous maintainer experience, I'll support as good as I can!

Thanks ❤️

**Comment by BrianMcBrayer** [comment]
I do not have time to be a fulltime maintainer, but I can probably pitch in and help a few times a month.

**Comment by fgreinacher** [comment]
> I do not have time to be a fulltime maintainer, but I can probably pitch in and help a few times a month.

Thanks! I'll just ping you from time to time 😀

**Comment by fgreinacher** [comment]
@tathamoddie @jpreese @robkeim Are you still interested in this project? If not would it be fine to remove you from the admins team?

**Comment by robkeim** [comment]
Hello @fgreinacher, you can go ahead and remove me from this project. I hope you're able to find some other maintainers to help share the load.

**Comment by tathamoddie** [comment]
> @tathamoddie @jpreese @robkeim Are you still interested in this project? If not would it be fine to remove you from the admins team?

I'm ok with you cleaning house and dropping me out of various admin groups / NuGet permissions / etc. 👍

Thank you for 4 amazing years of progress!!

I've posted a bit of a recruitment drive: https://twitter.com/TathamOddie/status/1480316292452085760

**Comment by tuan-tu-tran** [comment]
Hi, I don't have experience maintaining an open source project but I'd love to give it a shot!
Well at least pitch in.
Not sure how much time I can give at the moment.

**Comment by rkm** [comment]
Hi! We make heavy use of this fantastic package as part of our projects. I'm happy to chip-in and help if needed.

**Comment by fgreinacher** [comment]
Thanks @tuan-tu-tran @rkm @BrianMcBrayer for helping out here. Even the little things help a lot! I just added all of you to the project. Feel free to grab any issues and ping me if you need support. I think we're in a way better shape now, so I'm closing this issue.
