### ISSUE TITLE
`FileSystemInfo.LinkTarget` property is not exposed (this was added in .NET 6)

### ISSUE THREAD

**Issue by BrianMcBrayer** [TestableIO/System.IO.Abstractions#789]
**Describe the bug**
I _think_ (?) this is a bug because this is a property on `System.IO.FileSystemInfo` that is not on `System.IO.Abstractions.IFileSystemInfo`. This property was added in .NET 6 to help working with symlinks. See https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.linktarget?view=net-6.0

**To Reproduce**
1. Look at ApiParityTests.FileIno_.NET 6.0.snap
2. See that "System.String LinkTarget" is marked as a missing member

or

1. Write an app that needs to access `LinkTarget`

**Expected behavior**
I would expect `IFileSystemInfo` to have a `LinkTarget` property when this package is consumed by a .NET 6 app.

**Note**
I will be very happy to implement this. The only question I have is how does this project handle multitargetting? Any gotchas I need to know? Otherwise I'll add it and also add tests and such. I need this for something and want to help make it happen.

**Comment by BrianMcBrayer** [comment]
I've got the code almost ready to go. I need some guidance on adding to the test helpers--I'll put the PR up and we can discuss.

**Comment by fgreinacher** [comment]
Thanks for bringing this up! I'll try to answer your questions in the PR!
