### ISSUE TITLE
Make MockFileSystem able to simulate Unix paths

### ISSUE THREAD

**Issue by SuperJMN** [TestableIO/System.IO.Abstractions#800]
**Is your feature request related to a problem? Please describe.**
Currently, MockFileSystem works pretty much like a Windows file system, making it hard to test scenarios where an application has to deal with other different file system (for instance, Unix-based ones). I'm creating an application that deals with Windows paths and Unix paths at the same time and I need test that mapping from one to another works nicely. It interoperates with both types.

**Describe the solution you'd like**
 I'd like to have another helper, namely `MockUnixFileSsystem`, to be able to test these scenarios that use Unix-like paths. 

**Describe alternatives you've considered**
I've tried to create a custom implementation of IPath to override a custom MockFileSystem. It didn't work as expected.

**Comment by fgreinacher** [comment]
Thanks for the well-written issue @SuperJMN! It sounds very similar to #778 from my point-of-view. 

Could you check that one and see if my answers there help you a bit?
