### ISSUE TITLE
File.Exists throws an ArgumentException when empty string paths are used

### ISSUE THREAD

**Issue by masood-haloratech** [TestableIO/System.IO.Abstractions#810]
**Describe the bug**
MockFileSystem throws an System.ArgumentException ("The path is not of a legal form") when a empty string is passed to the File.Exists() method.

System.IO.File.Exists(string.Empty) returns false.

**To Reproduce**
```
        [Test]
        public void MockFile_Exists_ShouldReturnFalseForEmptyString()
        {
            // Arrange
            var fileSystem = new MockFileSystem();

            // Act
            var result = fileSystem.File.Exists(string.Empty);

            // Assert
            Assert.IsFalse(result);
        }
```

**Expected behavior**
fileSystem.File.Exists() should return false and behave like System.IO.File.Exists()

**Comment by fgreinacher** [comment]
Thanks for reporting!

Seems we don't respect https://docs.microsoft.com/en-us/dotnet/api/system.io.file.exists?view=net-6.0#remarks.

PR welcome 😀
