### ISSUE TITLE
MockFileInfo FullName property does not respect mocked filesystem

### ISSUE THREAD

**Issue by majora2007** [TestableIO/System.IO.Abstractions#831]
**Describe the bug**
When using a Mocked filesystem, using FullName on a MockedFileInfo, a drive that doesn't exist in the filesystem appears, thus breaking unit tests. 

**To Reproduce**
```
var fileSystem = new MockFileSystem();
fileSystem.AddFile($"/manga/input/file.zip", new MockFileData(""));
var targetFile = fileSystem.FileInfo.FromFileName(fileSystem.Path.Join("/manga/output/", "file.zip"))
Console.Writeline(targetFile.FullName)
```

**Expected behavior**
FullName should respect the mocked filesystem. In my case, it should output `/manga/output/file.zip`, while the actual output is `C:/manga/output/file.zip`.

**Additional context**
I noticed that DirectoryName, path, and FullName all share this issue.

**Comment by fgreinacher** [comment]
I assume you are running this on Windows? If so, the behavior is expected because we assume that the file system root (`C:` on Windows, `/` on Unix) exists in a fresh file system.

**Comment by majora2007** [comment]
That is indeed true, I'm using this on windows in some unit tests. However, my CI is on linux. Is there a solution to this? It seems strange that half the properties would keep the /manga/ base, as that is what I set the file up with, and a few of them would have C:/manga/. Doesn't seem like the behavior is in a unified front.

**Comment by majora2007** [comment]
I see, I thought using System.IO.Testable was the reason that we could mock the underlying system and not have to write extra code. Seems interesting that it works and shows correctly from `fileSystem.AddFile($"{testDirectory}file.zip", new MockFileData(""));` but just those inner fields which are used in my code path don't match the rest. Must be some inner implementation logic leaking to the interface that isn't changeable.

I'll take a look at using MockUnixSupport.Path, thanks.
