### ISSUE TITLE
Incorrect Creation and LastWriteTime properties on the FileInfo

### ISSUE THREAD

**Issue by TrevorNewsome76** [TestableIO/System.IO.Abstractions#838]
When using:

var fileInfo = FileSystem.FileInfo.FromFileName(<filename>);
fileInfo.CreationTime and fileInfo.LastWriteTime are incorrect.

**Comment by fgreinacher** [comment]
Could you share a bit more details? What version of the library are you using? What values to you expect and what is returned?

**Comment by TrevorNewsome76** [comment]
Please accept my sincere apologies, this is my mistake not the code base. I am using 3rd party code that implements the System.IO.Abstraction but creates the directory structure using files which are Embedded resources. It is due to them being Embedded resources and the lack of information that is available due to this where the issue is. I incorrectly presumed this implementation was part off the System.IO.Abstraction, but when I have spoken with the original developer it is not. This item can be closed.

**Comment by fgreinacher** [comment]
No worries, sometimes all it takes to understand a problem is asking the question 😀
