### ISSUE TITLE
Recursively delete a directory with readonly file results in inconsistent state

### ISSUE THREAD

**Issue by vbreuss** [TestableIO/System.IO.Abstractions#849]
**Describe the bug**
Recursively deleting a directory with read only file results in an inconsistent state of the `MockFileSystem`:
- The deletion results (as expected) in an `UnauthorizedAccessException`
- The file is still present (`File.Exists` returns `true`)
- The directory however is removed (`Directory.Exists` returns `false`)

**To Reproduce**
Consider the following unit test (using Xunit and FluentAssertions):
```csharp
    [Fact]
    public void DeleteDirectoryRecursive_WithReadOnlyFile_ShouldThrowExceptionAndNotDeleteDirectory()
    {
      var sut = new MockFileSystem();
      sut.Directory.CreateDirectory("foo");
      sut.File.WriteAllText("foo/bar.txt", "xyz");
      sut.File.SetAttributes("foo/bar.txt", FileAttributes.ReadOnly);
      
      var exception = Record.Exception(() =>
      {
        sut.Directory.Delete("foo", true);
      });

      exception.Should().BeAssignableTo<UnauthorizedAccessException>();
      sut.File.Exists("foo/bar.txt").Should().BeTrue();
      sut.Directory.Exists("foo").Should().BeTrue();
    }
```
This test fails at the last line, as the directory is deleted, although the file still exists, resulting in an inconsistent state of the `MockFileSystem`

**Expected behavior**
The unit test should be successful.

**Comment by fgreinacher** [comment]
Thanks for reporting! This would probably needs to be fixed in https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/System.IO.Abstractions.TestingHelpers/MockDirectory.cs#L118.

**Comment by VictorLlanir** [comment]
Hello, @fgreinacher, I would like to work on this issue.

**Comment by fgreinacher** [comment]
> Hello, @fgreinacher, I would like to work on this issue.

Thanks!

**Comment by VictorLlanir** [comment]
You're welcome, @fgreinacher! I've already opened a PR (#863) for this issue.
