### ISSUE TITLE
MockFile.ReadAllBytes returning the file contents, not a copy of them.

### ISSUE THREAD

**Issue by jamesmoore** [TestableIO/System.IO.Abstractions#853]
https://github.com/TestableIO/System.IO.Abstractions/blob/0326f629973eccdf68294982686f4ce258ca2ea3/src/System.IO.Abstractions.TestingHelpers/MockFile.cs#L541

If you do ReadAllBytes on a real System.IO.File you would have 2 independent copies, one on the FS and one in memory. My understanding of the linked code is that the mock would only produce one instance. Is this correct behavior or should it change? I am happy to push a PR if needed.

**Comment by fgreinacher** [comment]
You are right, we should not expose the internal array here. PR welcome 😄

**Comment by jamesmoore** [comment]
Fixed with this change: https://github.com/TestableIO/System.IO.Abstractions/pull/856
