### ISSUE TITLE
File.CreateSymbolicLink functionality is missing (Added in .net6.0)

### ISSUE THREAD

**Issue by davidrogers090** [TestableIO/System.IO.Abstractions#869]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use the `File.CreateSymbolicLink` and `Directory.CreateSymbolicLink` functionality in a testable way.

**Describe the solution you'd like**
The IFile.CreateSymbolicLink and IDirectory.CreateSymbolicLink and the default implementations available for use.

**Describe alternatives you've considered**
I could use the old way to create symbolic links, but this is messy and difficult to test.
I could invoke `cmd.exe mklink`, but this is not cross-platform and has serious security concerns.

**Additional context**
Related to #789.

**Comment by fgreinacher** [comment]
This makes a lot of sense, contributions welcome 👍

**Comment by davidrogers090** [comment]
I've begun working on this.  I should be able to do a PR soon.

**Comment by fgreinacher** [comment]
Thanks @davidrogers090! Feel free to ping me anytime for support/feedback!

**Comment by vbreuss** [comment]
I think this is now implemented with #965...
