### ISSUE TITLE
Set Creation, LastAccess and LastWrite time for files

### ISSUE THREAD

**Issue by vbreuss** [TestableIO/System.IO.Abstractions#872]
**Is your feature request related to a problem? Please describe.**
I want to test a functionality that relies on the "GetLastWriteTimeUtc" method to detect when a file was last changed.
This property in `MockFileSystem` only returns a fixed value "2010-02-03 20:00:00"

**Describe the solution you'd like**
`MockFileSystem` should set the creation, last access and last write times and return the correct values.
Ideally you would also provide an optional callback or property to set, so that I can even mock the time that is stored.

**Describe alternatives you've considered**
None, as the times are not even tracked anywhere internally.

**Additional context**
I would like e.g. the following unit test to pass:
```csharp
  [Theory]
  [WithAutoData]
  public void GetCreationTimeUtc_ShouldBeSet(string file)
  {
    var now = DateTime.UtcNow;
    var sut = new MockFileSystem();
    sut.File.WriteAllText("foo.txt", "xyz");

    var result = sut.File.GetCreationTimeUtc("foo.txt");

    result.Kind.Should().Be(DateTimeKind.Utc);
    result.Should().BeOnOrAfter(now);
  }
```

**Comment by fgreinacher** [comment]
We already have the partially, see https://github.com/TestableIO/System.IO.Abstractions/pull/861.

Makes sense to implement this consistently for all operations 👍

**Comment by vbreuss** [comment]
I would give it a try...
