### ISSUE TITLE
Support Async File Methods

### ISSUE THREAD

**Issue by vbreuss** [TestableIO/System.IO.Abstractions#881]
**Is your feature request related to a problem? Please describe.**
.NET Core (since 2.1) introduced async overloads for many File methods, e.g. [ReadAllTextAsync](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalltextasync?view=net-6.0).
As these are not part of the `IFileSystem` interface, I can't use async file access via this package.

**Describe the solution you'd like**
System.IO.Abstractions should support async file access for .NET Core

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by fgreinacher** [comment]
This has the same root cause as https://github.com/TestableIO/System.IO.Abstractions/issues/841 - sorry 😬

**Comment by vbreuss** [comment]
OK, thanks for the explanation!
