### ISSUE TITLE
IFileSystemWatcher dependency error

### ISSUE THREAD

**Issue by ascosmin09** [TestableIO/System.IO.Abstractions#937]
**Describe the bug**
When running the app: System.InvalidOperationException: Unable to resolve service for type 'System.IO.Abstractions.IFileSystemWatcher' while attempting to activate.

**To Reproduce**
1. Inject IFileSystemWatcher in the constructor like:

using System.IO.Abstractions;
namespace example;
public class ExampleClass{
      private readonly IFileSystemWatcher _fileSystemWatcher;
      public ExampleClass(IFileSystemWatcher fileSystemWatcher){
              this._fileSystemWatcher = fileSystemWatcher;
     }
}

2. Run the program.

**Expected behavior**
No error.

**Additional context**
-

**Comment by fgreinacher** [comment]
We don't provide out-of-the-box support for dependency injection frameworks, so I guess you need to do some bootstrapping, e.g. like [described in the .NET documentation](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-registration-methods).

**Comment by ascosmin09** [comment]
Can you please give me an example?
Is this the right way to do it?
    services.AddSingleton<IFileSystemWatcher>(sp => new FileSystemWatcherWrapper(new FileSystem()));
    services.AddSingleton<IFile>(sp=> new FileWrapper(new FileSystem()));
    services.AddSingleton<IDirectory>(sp=>new DirectoryWrapper(new FileSystem()));

**Comment by fgreinacher** [comment]
Not an expert, but this should be enough:

```csharp
services.AddSingleton<IFileSystem>(new FileSystem());
```
