### ISSUE TITLE
Release build of my application won't run without the mock dll

### ISSUE THREAD

**Issue by stephening** [TestableIO/System.IO.Abstractions#939]
First let me say this project is awesome!!!
It made it so much easier to write unit tests for my code.

Secondly, let me apologize in advance if this is not a bug and I am misunderstanding how it works or should be used, or If I'm using it incorrectly.

I used System.IO.Abstractions in my project, and I added System.IO.Abstractions.TestingHelpers to my test project. Everything worked great but then when I tried to release my application without the TestableIO.System.IO.Abstractions.dll my application wouldn't start. Maybe this is expected behavior, but I thought you should be able to release the app without the test helper dll's.

The behavior is that the app just doesn't show up and shuts down immediately.

**Comment by fgreinacher** [comment]
Do you have some repository that shows the problem? `TestableIO.System.IO.Abstractions` is always necessary, because it contains the interfaces. `TestableIO.System.IO.Abstractions.TestingHelpers` should usually only be added to test projects.

**Comment by stephening** [comment]
I will be uploading it to github soon. Sorry for the wait.

**Comment by fgreinacher** [comment]
Closing this as there was no more feedback.
