### ISSUE TITLE
FileInfoFactory and DirectoryInfoFactory Wrap implementations don't match the interface for nullability

### ISSUE THREAD

**Issue by mikeeheler** [TestableIO/System.IO.Abstractions#975]
**Describe the bug**
The implementations for `FileInfoFactory.Wrap` and `DirectoryInfoFactory.Wrap` require non-null references, while the interfaces are defined as `[return: NotNullIfNotNull("fileInfo")] IFileInfoFactory.Wrap(FileInfo? fileInfo)` and likewise for `IDirectoryInfoFactory.Wrap`.

**To Reproduce**
1. `new FileSystem().FileInfo.Wrap(null);`
2. The analyzer and compiler accept the syntax since `IFileInfoFactory.Wrap` accepts `FileInfo?` and returns `IFileInfo?`
3. An `ArgumentNullException` is thrown

**Expected behavior**
I expect to get a `null` `IFileInfo?` back if the input is `null`, and no exception thrown.

**Additional context**
Fixing this will help compatibility with [System.CommandLine](https://learn.microsoft.com/en-us/dotnet/standard/commandline/) where defining options as `FileInfo?` is a common practice, i.e.:

```csharp
var inputFileOption = new Option<FileInfo?>("--input");
var command = new Command("test") { inputFileOption };
command.SetHandler(
    (FileInfo? inputFile) => {
        var fileSystem = new FileSystem();
        var concreteCommand = new ConcreteCommand(fileSystem:fileSystem) {
            InputFile = fileSystem.FileInfo.Wrap(inputFile)
        }
        concreteCommand.Run();
    },
    inputFileOption
);
```

**Comment by vbreuss** [comment]
Thanks for creating this issue, @mikeeheler.
I already created a pull request (#976) to fix this bug!
