### ISSUE TITLE
IFileSystemInfo.ResolveLinkTarget throws exception instead of returning null if the path is not a link

### ISSUE THREAD

**Issue by zivarah** [TestableIO/System.IO.Abstractions#981]
**Describe the bug**
[System.IO.FileSystemInfo.ResolveLinkTarget](https://learn.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.resolvelinktarget?view=net-6.0#system-io-filesysteminfo-resolvelinktarget(system-boolean)) returns null when the directory is not a link.

IFileSystemInfo.ResolveLinkTarget ends up crashing with a null reference exception.

[ResolveLinkTarget implementation in DirectoryInfoWrapper.cs](https://github.com/TestableIO/System.IO.Abstractions/blob/main/src/TestableIO.System.IO.Abstractions.Wrappers/DirectoryInfoWrapper.cs#L43)
```C#
public override IFileSystemInfo ResolveLinkTarget(bool returnFinalTarget)
{
    return instance.ResolveLinkTarget(returnFinalTarget)
        .WrapFileSystemInfo(FileSystem);
}
```

[WrapFileSystemInfo implementation in Converters.cs](https://github.com/TestableIO/System.IO.Abstractions/blob/788d196afbf70dc7872dc8d72753e8052315fde6/src/TestableIO.System.IO.Abstractions.Wrappers/Converters.cs#L15)
```C#
private static FileSystemInfoBase WrapFileSystemInfo(IFileSystem fileSystem, FileSystemInfo item)
{
	if (item is FileInfo fileInfo)
	{
		return WrapFileInfo(fileSystem, fileInfo);
	}
	else if (item is DirectoryInfo directoryInfo)
	{
		return WrapDirectoryInfo(fileSystem, directoryInfo);
	}
	else
	{
		throw new NotImplementedException(string.Format(
			CultureInfo.InvariantCulture,
			"The type {0} is not recognized by the System.IO.Abstractions library.",
			item.GetType().AssemblyQualifiedName
		));
	}
}
```

The null reference we end up hitting is because `item` is null in WrapFileSystemInfo.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Object.GetType()
   at System.IO.Abstractions.Converters.WrapFileSystemInfo(IFileSystem fileSystem, FileSystemInfo item) in /home/runner/work/System.IO.Abstractions/System.IO.Abstractions/src/TestableIO.System.IO.Abstractions.Wrappers/Converters.cs:line 42
```

**To Reproduce**
```C#
IFileSystem fs = new FileSystem();
IDirectoryInfo dirinfo = fs.Directory.CreateDirectory(@"C:\Some\Dir");
IFileSystemInfo? target = dirinfo.ResolveLinkTarget(true); //Crash
```

**Expected behavior**
ResolveLinkTarget should propagate the null return of the underlying System.IO API one way or another.
That API could do it directly, though it seems like WrapFileSystemInfo really ought to do the propagation itself.

Fix option 1:
```C#
private static FileSystemInfoBase WrapFileSystemInfo(IFileSystem fileSystem, FileSystemInfo item)
{
	if (item == null)
	{
		return null;
	}
	...
}
```

Fix option 2:
```C#
public override IFileSystemInfo ResolveLinkTarget(bool returnFinalTarget)
{
    return instance.ResolveLinkTarget(returnFinalTarget)
        ?.WrapFileSystemInfo(FileSystem);
}
```

**Comment by zivarah** [comment]
I would be happy to submit a fix for this, but would like some input from the project team first. Was it an intentional decision to not propagate nulls in WrapFileSystemInfo?

**Comment by fgreinacher** [comment]
Wow, thanks for the detailed report, this is really appreciated!

> I would be happy to submit a fix for this, but would like some input from the project team first. Was it an intentional decision to not propagate nulls in WrapFileSystemInfo?

No, it is a bug. All the `Wrap*` methods should pass on `null` values. Feel free to submit a PR :bow:
